// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijdpfmxedytpgwapvaph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZHBmbXhlZHl0cGd3YXB2YXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDI5ODQsImV4cCI6MjA2ODAxODk4NH0.V43_-nKYIfGvQf7xQmcmIsBEr1t4CKAHICJRBSN5Knk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});